# File: .github/workflows/azure-static-web-apps.yml

name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change to your default branch
#   pull_request:
#     types: [opened, synchronize, reopened, closed]
#     branches:
#       - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Deploy Vite Frontend to Azure Static Website
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Use whatever your Vite project uses

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build Vite app
        run: npm run build
        working-directory: ./frontend

      - name: Deploy via Azure CLI
        run:
         az storage blob upload-batch \
            --account-name chenjrstorageaccount \
            --account-key ${{secrets.AZURE_STORAGE_KEY}} \ 
            --destination '$web' \
            --source./forntend/dist \
            --overwrite
         